spring:
  application:
    name: transfer-app
  profiles:
    active: local
    # Настройки продюсера
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.date-format: yyyy-MM-dd HH:mm:ss

    # Настройки консьюмера
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Разрешаем десериализацию JSON для указанных пакетов
        spring.json.trusted.packages: "com.bank.transfer.DTO"
        spring.json.value.default.type: com.bank.transfer.DTO.AuditDto
      group-id: transfer-group

