apiVersion: v1
kind: ConfigMap
metadata:
  name: anti-fraud-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOGGING_LEVEL_ROOT: "INFO"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5433/antifraud"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
