apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antifraud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: antifraud.example.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: antifraud-service
            port:
              number: 80
  tls:
  - hosts:
    - antifraud.example.com
    secretName: antifraud-tls
