spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/postgres?currentSchema=public_info}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public_info
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    default-schema: public_info
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
