apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOGGING_LEVEL_ROOT: "INFO"
  SERVER_PORT: "8087"
  SERVER_SERVLET_CONTEXT_PATH: "/api/authorization"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5433/postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_LIQUIBASE_DEFAULT_SCHEMA: "authorization"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
  SPRING_APPLICATION_NAME: "authorization-app"
  MANAGEMENT_SERVER_PORT: "8187" 