apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorization-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authorization-role
rules:
  - apiGroups: [""]
    resources: ["configmaps","secrets"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authorization-rb
subjects:
  - kind: ServiceAccount
    name: authorization-sa
roleRef:
  kind: Role
  name: authorization-role
  apiGroup: rbac.authorization.k8s.io 