apiVersion: v1
kind: Secret
metadata:
  name: authorization-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"
  JWT_SECRET: "984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf"
  JWT_LIFETIME: "3600000" 